"""add google oauth fields

Revision ID: cf516ed6e578
Revises: 16704bbfa078
Create Date: 2025-03-09 02:28:39.062322

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf516ed6e578'
down_revision: Union[str, None] = '16704bbfa078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_token', sqlmodel.sql.sqltypes.AutoString()))
    op.add_column('user', sa.Column('google_token_expires', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # set the google_token column for existing users to an empty string
    old_users = sa.table('user', sa.column('google_token'))
    op.execute(old_users.update().values(google_token=''))
    # now make the google_token column not nullable
    op.alter_column('user', 'google_token', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_token_expires')
    op.drop_column('user', 'google_token')
    # ### end Alembic commands ###
