"""chat and chat_message

Revision ID: 1740404554
Revises: 1739834110
Create Date: 2025-02-24 14:42:34.970557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1740404554'
down_revision: Union[str, None] = '1739834110'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update User table: make 'picture' nullable
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("picture", nullable=True)

    # Create Chat table
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"])
    )

    # create ChatMessage table
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("sender", sa.String(length=32), nullable=False),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"])
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update User table: make 'picture' not nullable
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("picture", nullable=False)

    # Drop Chat table
    op.drop_table("chat")

    # Drop ChatMessage table
    op.drop_table("chat_message")
    # ### end Alembic commands ###
